- name: docker installer
  hosts: "{{ hosts }}"
  tasks:
    - name: docker installer
      vars:
        ansible_become: true
        ansible_become_method: sudo
        ansible_become_password: 123
      shell: echo "healthy"
      register: result
    - debug:
        msg: "{{result.stdout}}"
