- name: Kubernetes Installer
  hosts: '{{ hosts }}'
  tasks:
    - name: KUBERNETES INSTALLER
      vars:
        ansible_become: true
        ansible_become_method: sudo
        ansible_become_password: 123
      shell: |
        echo "hello"
      register: result
    - debug:
        msg: "{{result.stdout}}"
