- name: docker installer
  hosts: '{{ hosts }}'
  tasks:
    - name: DOCKER INSTALLER
      vars:
        ansible_become: true
        ansible_become_method: sudo
        ansible_become_password: 123
      shell: |
        echo "# Add Docker's official GPG key:\n"
        apt-get update
        apt-get install ca-certificates curl gnupg
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --yes --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg

        echo "\n# Add the repository to Apt sources:\n"
        echo \
          "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
          tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update

        echo "\n# install docker\n"
        apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      register: result
    - debug:
        msg: "{{result.stdout}}"
          
    - name: REMOVE SU USER PERMISSION...
      vars:
        ansible_become: true
        ansible_become_method: sudo
        ansible_become_password: 123
      shell: |
        usermod -aG docker ${USER}
        chmod 666 /var/run/docker.sock
        service docker restart
        echo "\nremove su user permission complete!!!\n"
      register: result
    - debug:
        msg: "{{result.stdout}}"
